{% set name = "cinemagoer" %}
{% set version = "2022.12.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cinemagoer-{{ version }}.tar.gz
  sha256: 63006016752567c14e1a63a24190cfa44963228116b282303632f7279e9f4ae7

build:
  entry_points:
    - imdbpy = imdb.cli:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
    - polib
  run:
    - lxml
    - python >=3.6
    - sqlalchemy
    - polib

test:
  imports:
    - imdb
  commands:
    - pip check
    - imdbpy --help
  requires:
    - pip

about:
  home: https://cinemagoer.github.io/
  summary: Python package to access the IMDb's database
  description: |
    Cinemagoer is a Python package useful to retrieve and manage the data of the IMDb (to which we are not affiliated in any way) movie database about movies, people, characters and companies
  license: GPL-2.0-or-later
  dev_url: https://github.com/cinemagoer/cinemagoer
  doc_url: https://cinemagoer.readthedocs.io/
  license_file:
    - LICENSE.txt

extra:
  recipe-maintainers:
    - HeavyTony2
