{% set name = "cinemagoer" %}
{% set version = "2026.8.20" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/cinemagoer-{{ version }}.tar.gz
  sha256: 99b99fe30582ddbfb08db0dd8af712bd55c11da7c3155e07a19ac6b5ecd677aa

build:
  entry_points:
    - imdbpy = imdb.cli:main
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - lxml >=6.1.1
    - python >={{ python_min }}
  run_constrained:
    - sqlalchemy >=2.0.51,<2.1

test:
  imports:
    - imdb
  commands:
    - pip check
    - imdbpy --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://cinemagoer.github.io/
  summary: Python package to access the IMDb's database
  description: |
    Cinemagoer is a Python package useful to retrieve and manage the data of the IMDb (to which we are not affiliated in any way) movie database about movies, people, characters and companies
  license: GPL-2.0-only
  dev_url: https://github.com/cinemagoer/cinemagoer
  doc_url: https://cinemagoer.readthedocs.io/
  license_file:
    - LICENSE.txt

extra:
  recipe-maintainers:
    - HeavyTony2
